---
- name: sudo | Install sudo package
  ansible.builtin.apt:
    name: sudo
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: sudo | Install sudo package (RedHat)
  ansible.builtin.yum:
    name: sudo
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: sudo | Update sudoers
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: "0440"
    validate: "visudo -cf %s"
    backup: true
  notify: reset connection
